### ISSUE TITLE
how to add any drawable resource as indicator in active and inactive ?

### ISSUE THREAD

**Issue by nikulvaghani** [markusressel/PageIndicatorView#7]

**Comment by markusressel** [comment]
That is currently not possible. A drawable would make animations pretty hard. If you don't need them you can try to exchange the `activeIndicator` and `inactiveIndicator` implementations of the `PageIndicatorView` class to not use the `CircleIndicatorView` class but an ImageView or something similar.

**Comment by nikulvaghani** [comment]
@markusressel im talking about drawable selector or shape not an image.

**Comment by markusressel** [comment]
It's the same problem. The `CircleIndicatorView` that is used for each "dot" draws circles directly onto the canvas so it doesn't support custom shapes. 
See https://github.com/markusressel/PageIndicatorView/blob/ade1d63a3a2d81d073037b162c57ebad312ff394/library/src/main/java/de/markusressel/android/library/pageindicatorview/CircleIndicatorView.kt#L175

If you want to use a custom shape you would need to replace that.
